#!/bin/bash

echo "WARNING: Running this script directly from upstream/the unstable branch can cause issues (possibly even breaking/bricking Roblox, command-line or your system)!"

if [ -z "$1" ]
  then
    targetFps=10000
  else
    targetFps=$1
fi

robloxPath="/Applications/Roblox.app"

if [ -z "$robloxPath" ]; then
  $robloxPath="~/Applications/Roblox.app"
  if [ -z "$robloxPath" ]; then
    echo "WARNING: Couldn't find Roblox.app using default paths. Are you sure you want to use 'find' as a last resort? (yes/no)"
    read useFindMethod
    case $useFindMethod in
      yes)
        $robloxPath=$(find /Applications -name Roblox.app -print -quit 2>/dev/null)
        if [ -z "$robloxPath" ]; then
          $robloxPath=$(find ~/Applications -name Roblox.app -print -quit 2>/dev/null)
          if [ -z "$robloxPath" ]; then
            echo "ERROR: Roblox installation folder couldn't be found."
            exit 1
          fi
        fi
        ;;
      no)
        echo "ERROR: Roblox installation folder couldn't be found."
        exit 1
        ;;
      *)
        echo "Unknown option."
        exit 1
        ;;
    esac
  fi
fi

clientSettingsPath="$robloxPath/Contents/MacOS/ClientSettings"

if [ ! -d "$clientSettingsPath" ]; then
  mkdir $clientSettingsPath
fi

if [[ -z "$2" ]]; then
    echo "Do you want to use the Vulkan renderer? This will remove the FPS cap completely, but might break Roblox if you use an external monitor. (yes/no): "
    read useVulkan
elif [[ "$2" == "yes" ]]; then
    useVulkan=yes
elif [[ "$2" == "no" ]]; then
    useVulkan=no
elif [[ "$2" == "y" ]]; then
    useVulkan=yes
elif [[ "$2" == "n" ]]; then
    useVulkan=no
else
    echo "Do you want to use the Vulkan renderer? This will remove the FPS cap completely, but might break Roblox if you use an external monitor. (yes/no): "
    read useVulkan
fi

case $useVulkan in
  yes)
    clientSettings=" \
    { \
      \"DFIntTaskSchedulerTargetFps\": $targetFps, \
      \"FFlagDebugGraphicsDisableMetal\": \"true\", \
      \"FFlagDebugGraphicsPreferVulkan\": \"true\" \
    } \
    "
    ;;

  no)
    clientSettings=" \
    { \
      \"DFIntTaskSchedulerTargetFps\": $targetFps \
    } \
    "
    ;;

  *)
    echo "Unknown option."
    exit 1
    ;;
esac

echo $clientSettings > "$clientSettingsPath/ClientAppSettings.json"

echo "The FPS unlocker has been installed in $robloxPath."
