#!/bin/sh

if [ -z "$1" ]
  then
    targetFps=10000
  else
    if [ "$1" = "y" ]; then
      useVulkan=$1
    elif [ "$1" = "yes" ]; then
      useVulkan=$1
    elif [ "$1" = "n" ]; then
      useVulkan=$1
    elif [ "$1" = "no" ]; then
      useVulkan=$1
    else
      targetFps=$1
    fi
fi
robloxPath=$(find /Applications -name Roblox.app -print -quit 2>/dev/null)

if [ -z "$robloxPath" ]; then
  $robloxPath=$(find /Applications -name RobloxPlayer.app -print -quit 2>/dev/null)
  if [ -z "$robloxPath" ]; then
    $robloxPath=$(find ~/Applications -name Roblox.app -print -quit 2>/dev/null)
    if [ -z "$robloxPath" ]; then
      $robloxPath=$(find ~/Applications -name RobloxPlayer.app -print -quit 2>/dev/null)
      if [ -z "$robloxPath" ]; then
         echo "Roblox installation folder couldn't be found."
         exit
      fi
    fi
  fi
fi

clientSettingsPath="$robloxPath/Contents/MacOS/ClientSettings"

if [ ! -d "$clientSettingsPath" ]; then
  mkdir $clientSettingsPath
fi

echo "Do you want to use the Vulkan renderer? This will remove the FPS cap completely, but might break Roblox if you use an external monitor. (yes/no): "
if [ -z "$useVulkan" ]; then
  if [ -z "$2" ]; then
    read useVulkan
  else
    if [ "$1" = "y" ]; then
      useVulkan=$2
    elif [ "$1" = "yes" ]; then
      useVulkan=$2
    elif [ "$1" = "n" ]; then
      useVulkan=$2
    elif [ "$1" = "no" ]; then
      useVulkan=$2
    else
      echo "Unknown option."
      exit 1
    fi
  fi
fi

case $useVulkan in
  yes)
    clientSettings=" \
    { \
      \"DFIntTaskSchedulerTargetFps\": $targetFps, \
      \"FFlagDebugGraphicsDisableMetal\": \"true\", \
      \"FFlagDebugGraphicsPreferVulkan\": \"true\" \
    } \
    "
    ;;

  no)
    clientSettings=" \
    { \
      \"DFIntTaskSchedulerTargetFps\": $targetFps \
    } \
    "
    ;;

  y)
    clientSettings=" \
    { \
      \"DFIntTaskSchedulerTargetFps\": $targetFps, \
      \"FFlagDebugGraphicsDisableMetal\": \"true\", \
      \"FFlagDebugGraphicsPreferVulkan\": \"true\" \
    } \
    "
    ;;

  n)
    clientSettings=" \
    { \
      \"DFIntTaskSchedulerTargetFps\": $targetFps \
    } \
    "
    ;;

  *)
    echo "Unknown option."
    exit 1
    ;;
esac

echo $clientSettings > "$clientSettingsPath/ClientAppSettings.json"

echo "The FPS unlocker has been installed in $robloxPath."
