# This is a basic workflow to help you get started with Actions

name: Test rbxfpsunlocker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "script" branch
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Test rbxfpsunlocker
        run: |
          curl -sfLO https://raw.githubusercontent.com/92959/rbxfpsunlocker-osx/testing/install_fps_unlocker
          chmod +x ./install_fps_unlocker
          mkdir -p /Applications/Roblox.app/Contents/MacOS/ClientSettings
          ./install_fps_unlocker 144 yes
          cat /Applications/Roblox.app/Contents/MacOS/ClientSettings/ClientAppSettings.json
